### ISSUE TITLE
average time per frame

### ISSUE THREAD

**Issue by shenhai911** [Runsong123/AdaFit#4]
Dear authors,
Thank you for your great work.
I want to know the processing time per frame.
Thank you very much for for your reply.

**Comment by Runsong123** [comment]
> Dear authors, Thank you for your great work. I want to know the processing time per frame. Thank you very much for for your reply.

Hi, thanks for your interest.

For the processing time, it will depond on the input clouds due to that we need to input a local patch to inference the normal vector for a single point. Right now, I can not remember the exactly time. But you can refer to the runing time of DeepFit on PCPNet, the speed of single version of AdaFit is similiar to DeepFit.

Best,
Runsong

**Comment by shenhai911** [comment]
Ok, thank you very much for your prompt reply, and I will look for the answer from the DeepFit.

**Comment by Runsong123** [comment]
> Ok, thank you very much for your prompt reply, and I will look for the answer from the DeepFit.

BTW, you can find the reuslt in DeepFit's paper (supp part).

Best,
Runsong
